// HOST AND JOIN TO BE COMBINED INTO JUST "MULTIPLAYER" LATER
global.MENU_INDEX = 0;
global.MENU_OPTIONS = ["SINGLEPLAYER", "MULTIPLAYER HOST", "MULTIPLAYER JOIN", "SETTINGS", "CREDITS", "EXIT"];

global.IS_MULTIPLAYER = false;

enum PACKETS {
	INIT,
	EVENT,
	CONTINUOUS,
}

enum EVENTS {
	PLAYER_DAMAGED,
	
}