global.MENU_INDEX = 0;
// HOST AND JOIN TO BE COMBINED INTO JUST "MULTIPLAYER" LATER
global.MENU_OPTIONS = ["SINGLEPLAYER", "MULTIPLAYER HOST", "MULTIPLAYER JOIN", "SETTINGS", "CREDITS", "EXIT"];

global.IS_MULTIPLAYER = false;