name: Automate Tag Versioning and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automate_versioning_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Find Latest Tag
        id: find_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --always)
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Increment Tag
        id: increment_tag
        run: |
          latest_tag=$(echo "${LATEST_TAG}")
          major=$(echo $latest_tag | cut -d'.' -f1)
          minor=$(echo $latest_tag | cut -d'.' -f2)
          patch=$(echo $latest_tag | cut -d'.' -f3)
          new_tag="$major.$minor.$((patch + 1))"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}  # Use env.NEW_TAG from the environment file
          release_name: Release ${{ env.NEW_TAG }}
          body: Automated release notes. Add details about changes, fixes, etc.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
