name: Test Project

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
    - main
      
permissions:
  contents: write  # Ensure the action has write access to contents

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "::set-output name=tag::$latest_tag"
      - name: Increment tag
        id: increment_tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.tag }}"
          major_version=$(echo "$latest_tag" | cut -d. -f1 | sed 's/v//')
          next_major_version=$((major_version + 1))
          new_tag="v$next_major_version.0.0"
          echo "::set-output name=next_tag::$new_tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.next_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.next_tag }}
          body: |
            Example release notes
