name: Build and Export GameMaker Project

on:
  push:
    branches:
      - main
    # paths-ignore:
      # - '.github/workflows/**' 

jobs:
  get_version:
    name: Get Latest Version Tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.new_tag.outputs.tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "::set-output name=tag::$latest_tag"
          
      - name: Bump version
        id: new_tag
        run: |
          if [ -z "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            new_tag="v1.0.0"
          else
            latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
            IFS='.' read -r -a parts <<< "${latest_tag#v}"
            major=${parts[0]}
            minor=${parts[1]}
            patch=${parts[2]}
            new_tag="v$major.$((minor + 1)).0"
          fi
          echo "New tag: $new_tag"
          echo "::set-output name=tag::$new_tag"
          
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get_version.outputs.new_tag }}
          release_name: Release ${{ needs.get_version.outputs.new_tag }}
          body: |
            Automated release notes. Add details about changes, fixes, etc.
          draft: false
          prerelease: false
