name: Automate Tag Versioning and Release

on:
  push:
    branches:
      - main
    # paths-ignore:
      # - '.github/workflows/**'
  

permissions:
  contents: write

jobs:
  check_inventory_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run inventory check script
      run: |
        # Read the inventory_testing.txt file line by line
        while IFS= read -r line
        do
          # Remove trailing whitespace
          line=$(echo "$line" | sed 's/[[:space:]]*$//')
          # Extract the last word from each line
          last_word=$(echo "$line" | awk '{print $NF}')
          # Check if the last word is "Passed"
          if [ "$last_word" != "Passed" ]; then
            echo "Error: The line '$line' does not end with 'Passed'"
            exit 1
          fi
        done < inventory_testing.txt
        
  automate_versioning_and_release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
          #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
          
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.semvers.outputs.v_major }} 
          release_name: Release ${{ steps.semvers.outputs.v_major }}
          body: Automated release notes. Add details about changes, fixes, etc.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
